version: '3.10'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:1234321@db:5432/user_select
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_select
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234321

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres_data:
