# Generated by Django 5.1.3 on 2024-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('crm_admin', 'CRM-менеджер')], max_length=20)),
                ('offer', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='default.png', upload_to='avatars/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
